sonar.projectKey=VidiomTM_ObstetraScroll
sonar.organization=vidiomtm
sonar.autoscan.enabled=false

# Source
sonar.sources=src
sonar.exclusions=tests/**,test-results/**,**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Duplications
sonar.cpd.exclusions=tests/**,**/*.test.ts,**/*.spec.ts,**/*.svelte

# Quality gate
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

# TypeScript analysis
sonar.typescript.tsconfigPath=tsconfig.json
sonar.typescript.exclusions=**/*.test.ts,**/*.spec.ts

# Svelte
sonar.svelte.enabled=true
